config/routes.rb
CheckMate::Application.routes.draw do
  devise_for :users
  resources :checkins do
    collection do
      get 'test_email'
    end
  end

  root :to => 'home#index'

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  belongs_to :user
  attr_accessible :job_id, :conf, :first, :last, :time_zone, :time
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, #:confirmable,
         :lockable, :timeoutable 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :checkins, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  
  include CheckinsHelper
  
  def index
    @checkins = current_user.checkins
  end
  
  def show
    @checkin = Checkin.find(params[:id])
  end
  
  def new
    @checkin = Checkin.new
  end
  
  def create
    @checkin = current_user.checkins.create(params[:checkin])
    month = params[:date][:month]
    day = params[:date][:day]
    year = params[:date][:year]
    hour = params[:date][:hour]
    minute = params[:date][:minute]
    @checkin.time = "#{month}/#{day}/#{year} #{hour}:#{minute}"
    @checkin.time_zone = params[:checkin][:time_zone]
    
    if @checkin.save
      schedule_checkin(@checkin)
      redirect_to @checkin
    else
      render :action => "new"
    end
  end
  
  def edit
    @checkin = Checkin.find(params[:id])
  end
  
  def destroy
    @checkin = Checkin.find(params[:id])
    unschedule_checkin(@checkin)
    @checkin.destroy
    redirect_to checkins_url
  end
  
  def test_email
    UserMailer.delay.test_email(current_user)
    redirect_to checkins_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    redirect_to checkins_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
  
  require 'net/http'
  require 'uri'
  
  @@PROTOCOL = "http://"
  @@HOST = "www.southwest.com"
  @@URL_RETRIEVE = "/flight/retrieveCheckinDoc.html"
  
  @@scheduler = Rufus::Scheduler.start_new
  
  def init_scheduler
    schedule_all_checkins  
  end
  
  def do_checkin(checkin)
    url = URI.parse("#{@@PROTOCOL}#{@@HOST}#{@@URL_RETRIEVE}")
    res = Net::HTTP.post_form(url,{
      "formToken" => "",
      "confirmationNumber" => checkin.conf,
      "firstName" => checkin.first,
      "lastName" => checkin.last,
      "submitButton" => "Check In"})   
    case res
    when Net::HTTPRedirection then
    else
      puts "Step 1: Not a 302"
      return
    end
    url = URI.parse(res['location'])
    req = Net::HTTP::Post.new(url.request_uri)
    req.set_form_data({
      "formToken" => "",
      "checkinPassengers[0].selected" => "true",
      "printDocuments" => "Check In"},'&')
    res = Net::HTTP.new(url.host, url.port).start {|http| http.request(req) }
    case res
    when !Net::HTTPRedirection then 
      puts "Step 2: Not a 302"
      return
    end
    url = URI.parse(res['location'])
    res = Net::HTTP.get_response(url)
    case res
    when Net::HTTPSuccess then 
    else
      puts "Step 3: Not a 200"
      return
    end
    @checkin.destroy
  end
  
  def schedule_checkin(checkin)
    Chronic.time_class = ActiveSupport::TimeZone.create(checkin.time_zone)
    time = DateTime.parse(Chronic.parse(checkin.time).to_s)
    time = (time.to_time - 1.day).to_datetime
    Rails.logger.debug("TIME: #{time}")
    job = @@scheduler.at time do
      do_checkin(checkin)
    end
    checkin.job_id = job.job_id
    checkin.save
  end
  
  def unschedule_checkin(checkin)
    @@scheduler.unschedule(checkin.job_id)
  end
  
  def schedule_all_checkins
    if !Checkin.table_exists?
      return
    end
    Checkin.all.each do |checkin|
      schedule_checkin(checkin)
    end
  end
  
  def get_scheduled_job(checkin)
    return @@scheduler.find(checkin.job_id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/checkins/_form.html.erb
<%= form_for(@checkin) do |form| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @checkin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= form.label :first %></td>
      <td><%= form.text_field :first %></td>
    </tr>
    <tr>
      <td><%= form.label :last %></td>
      <td><%= form.text_field :last %></td>
    </tr>
    <tr>
      <td><%= form.label :conf %></td>
      <td><%= form.text_field :conf %></td>
    </tr>
    <tr>
      <td><%= label_tag(:flight_time, "Flight Time:") %></td>
      <td><%= select_datetime(Time.now) %></td>
      <td>(Time of flight)</td>
    </tr>
    <tr>
      <td><%= label_tag(:time_zone, "Time Zone:") %></td>
      <td><%= time_zone_select(:checkin, :time_zone, ActiveSupport::TimeZone.us_zones, :default => "Pacific Time (US & Canada)") %></td>
    </tr>
  </table>
  <%= form.submit %>
<% end %>

app/views/checkins/edit.html.erb
<h1>Edit Checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %>

app/views/checkins/index.html.erb
<table>
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Conf</th>
    <th>Time</th>
    <th></th>
    <th></th>
  </tr>

<% @checkins.each do |checkin| %>
  <tr>
    <td><%= checkin.first %></td>
    <td><%= checkin.last %></td>
    <td><%= checkin.conf %></td>
    <td><%= checkin.time %></td>
    <td><%= link_to 'Show', checkin %></td>
    <td><%= link_to 'Destroy', checkin, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Checkin', new_checkin_path %>
<%= link_to 'Test Email', test_email_checkins_path %>

app/views/checkins/new.html.erb
<h1>New Checkin</h1>

<%= render 'form' %>

app/views/checkins/show.html.erb
<% job = get_scheduled_job(@checkin) %>
<h1>Checkin Details</h1>

<table>
  <tr>
    <td>First:</td>
    <td><%= @checkin.first %></td>
  </tr>
  <tr>
    <td>Last:</td>
    <td><%= @checkin.last %></td>
  </tr>
  <tr>
    <td>Conf:</td>
    <td><%= @checkin.conf %></td>
  </tr>
  <tr>
    <td>Flight Time:</td>
    <td><%= @checkin.time %></td>
  </tr>
  <tr>
    <td>Time Zone:</td>
    <td><%= @checkin.time_zone %></td>
  </tr>
  <tr>
    <td>Checkin At:</td>
    <td><%= job.next_time %></td>  
  </tr>
</table>

<%= link_to 'Back to Checkins', checkins_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckMate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
      
<%= yield %>

<br/>
<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>

</body>
</html>